version: '3.6'
networks:
  internal-net:
   name: payara_subnet
services:
  server:
    image: payara/server-full:5.183
    container_name: payara
    networks:
      - internal-net
    volumes:
      - ./war:/opt/payara/deployments
    ports:
      - "8080:8080"
