version: '3.6'
networks:
  internal-net:
   name: payara_subnet
services:
  server:
    image: ninrod/payara:0.0.1
    container_name: payara
    networks:
      - internal-net
    volumes:
      - ./backend/target/ping.war:/opt/payara/deployments/ping.war
    ports:
      - "8080:8080"
      - "4848:4848"
      - "8009:8009"
      - "8181:8181"
  db:
    image: postgres:10.5
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - internal-net
